name: CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x.x

      - name: Install Workloads
        run: dotnet workload install android ios wasm-tools

      - name: Build Release
        run: dotnet build -c Release

  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x.x

      - name: Build Release Desktop
        run: dotnet build -c Release src/Project.Desktop

  build-macos:
    name: Build MacOS 13
    runs-on: macos-13
    steps:

      - name: Select xcode version
        run: sudo xcode-select -s /Applications/Xcode_14.3.app/Contents/Developer/

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x.x

      - name: Install Workloads
        run: dotnet workload install android ios wasm-tools

      - name: Build Release
        run: dotnet build -c Release
